// function to give .grid-item a unique background image for each instance of a .grid-item from an array of images
const images = 
[
"/images/2.png",
"/images/b1.png",
"/images/k1.png",
"/images/o1.png",
"/images/3.png",
"/images/k2.png",
"/images/1.png",
"/images/b2.png",
"/images/a1.png",
"/images/4.png",
"/images/o2.png",
"/images/b3.png",
"/images/a2.png",
"/images/03.png",
"/images/b4.png",
"/images/a4.png",
"/images/6.png",
"/images/k3.png",
"/images/b5.png",
"/images/7.png",
"/images/b6.png",
"/images/k4.png",
"/images/b5.png",
"/images/a5.png",
"/images/8.png",
"/images/9.png",
"/images/b5.png",
"/images/a5.png",
"/images/10.png",
"/images/k5.png",
"/images/b6.png",
"/images/a6.png",
"/images/11.png",
"/images/k6.png",
"/images/b7.png",
"/images/a6.png",
"/images/12.png",
"/images/o2.png",
"/images/k7.png",
"/images/b7.png",
"/images/19.png",
"/images/o3.png",
"/images/14.png",
"/images/k8.png",
"/images/b8.png",
"/images/15.png",
"/images/o4.png",
"/images/16.png",
"/images/k9.png",
"/images/b9.png",
"/images/17.png",
"/images/o5.png",
"/images/18.png",
"/images/k10.png",
"/images/b10.png",
"/images/k11.png",
"/images/o6.png",
"/images/b11.png",
]

const gridItems = document.querySelectorAll('.grid-item');
// const images = [image, 'image2.jpg', 'image3.jpg', 'image4.jpg'];

gridItems.forEach((gridItem, index) => {
  gridItem.style.backgroundImage = `url(${images[index]})`;
});